config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'sign-up', to: 'registrations#new'
  post 'sign-up', to: 'registrations#create'
  get 'sign-in', to: 'authentication#new'
  post 'sign-in', to: 'authentication#create'

  resources :cheeses
end

app/models/cheese.rb
class Cheese < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def ensure_current_user
    unless current_user
      redirect_to root_path
      flash[:notice] = 'You must register or log in before you can do that!'
    end
  end

  def current_user
    User.find_by(id: session[:user_id])
  end

  helper_method :current_user
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to cheeses_path
      flash[:notice] = "Successfully signed in"
    else
      flash[:notice] = 'User could not be authenticated. Please try again.'
      render :new
    end
  end




end

app/controllers/cheeses_controller.rb
class CheesesController < ApplicationController
  before_action :ensure_current_user

  def index
    @cheeses = Cheese.all
  end

  def new
    @cheese = Cheese.new
  end

  def create
    @cheese = Cheese.new(cheese_params)

    if @cheese.save
      redirect_to cheeses_path
      flash[:notice] = "Cheese created successfully!"
    else
    end
  end

  def show
    @cheese = Cheese.find(params[:id])
  end

  def edit
    @cheese = Cheese.find(params[:id])
  end

  def update
    @cheese = Cheese.find(params[:id])

    if @cheese.update(cheese_params)
      redirect_to cheese_path(@cheese)
      flash[:notice] = "Cheese updated successfully!"
    else
      render :edit
    end
  end

  def destroy
    @cheese = Cheese.find(params[:id])

    @cheese.destroy

    redirect_to cheeses_path
    flash[:notice] = "Deleted cheese: #{@cheese.name}"
  end



  def cheese_params
    params.require(:cheese).permit(:name, :price_per_lb)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Successfully signed up"
      redirect_to cheeses_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentication/new.html.erb
Sign In Form

<%= form_tag sign_in_path do |f| %>

  <%= label_tag :email %>
  <%= email_field_tag :email %>

  <%= label_tag :password %>
  <%= password_field_tag :password %>

  <%= submit_tag "Sign in" %>



<% end %>

app/views/cheeses/edit.html.erb
<%= form_for @cheese do |f| %>

  <%= f.label :name %>
  <%= f.email_field :name %>

  <%= f.label :price_per_lb%>
  <%= f.password_field :price_per_lb %>

  <%= f.submit "Update Cheese" %>

<% end %>

app/views/cheeses/index.html.erb
List of Cheeses

<% @cheeses.each do |cheese| %>
  <%= link_to "#{cheese.name} - $#{cheese.price_per_lb}", cheese_path(cheese)%>
<% end %>

<%= link_to "New Cheese", new_cheese_path(@cheese) %>

app/views/cheeses/new.html.erb
<%= form_for @cheese do |f| %>

  <%= f.label :name %>
  <%= f.email_field :name %>

  <%= f.label :price_per_lb%>
  <%= f.text_field :price_per_lb %>

  <%= f.submit "Create Cheese" %>

<% end %>

app/views/cheeses/show.html.erb
Cheese Name: <%= @cheese.name %>
<br>
Cheese Price ($/lb): $<%= @cheese.price_per_lb %>

<%= link_to "Index", cheeses_path %>
<%= link_to "Edit", edit_cheese_path(@cheese) %>
<%= link_to "Destroy", cheese_path(@cheese), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CheeseBam</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:notice] %>
<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
Welcome, please click the sign up or sign in links below

<%= link_to "Sign up", sign_up_path %>
<%= link_to "Sign in", sign_in_path %>